language: ruby
matrix:
  include:
    - rvm: 2.2.2
      env: BUNDLER_DOWNGRADE=1
    - rvm: 2.4.0
      env: BUNDLER_DOWNGRADE=1
    - rvm: 2.5.3
      env: BUNDLER_UPGRADE=1
before_install:
  - sh -c "if [ '$BUNDLER_UPGRADE' = '1' ]; then gem update --system; fi"
  - sh -c "if [ '$BUNDLER_UPGRADE' = '1' ]; then gem install bundler; fi"
  - sh -c "if [ '$BUNDLER_DOWNGRADE' = '1' ]; then gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true; fi"
  - sh -c "if [ '$BUNDLER_DOWNGRADE' = '1' ]; then gem install bundler -v '< 2'; fi"
  - gem install origen
script:
  - origen -v
  - origen m debug
  - origen test -c
  - origen web compile --no-serve
  - origen lint --no-correct
env:
  - ORIGEN_GEM_USE_FROM_SYSTEM=false ORIGEN_GEM_MANAGE_BUNDLER=false
