language: ruby
matrix:
  include:
    - rvm: 2.2.2
      env: BUNDLER_OP=NONE
    - rvm: 2.4.0
      env: BUNDLER_OP=DOWNGRADE
    - rvm: 2.5.3
      env: BUNDLER_OP=UPGRADE
before_install:
  - if [ "$BUNDLER_OP" = "UPGRADE" ]; then gem update --system; fi
  - if [ "$BUNDLER_OP" = "UPGRADE" ]; then gem install bundler; fi
  - if [ "$BUNDLER_OP" = "DOWNGRADE" ]; then gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true; fi
  - if [ "$BUNDLER_OP" = "DOWNGRADE" ]; then gem install bundler -v '< 2'; fi
  - if [ "$BUNDLER_OP" = "NONE" ]; then gem install bundler; fi
script:
  - bundle exec origen -v
  - bundle exec origen m debug
  - bundle exec origen test -c
  - bundle exec origen web compile --no-serve
  - bundle exec origen lint --no-correct
env:
  - ORIGEN_GEM_USE_FROM_SYSTEM=false ORIGEN_GEM_MANAGE_BUNDLER=false
