# GEM SETUP

# If your company has an internal gem server enter it here
#gem_server: http://gems.company.net:9292

# When true Origen will configure and run Bundler in a consistent way for every
# user (recommended)
gem_manage_bundler: true

# Define where a typical user's home directory will be, with a hidden directory for Origen.
home_dir: ~/.origen

# Define where the gems should be installed
# By default, this will be at <home_dir>/gems but can be overridden here.
#gem_install_dir: ~/.origen/gems

# ORIGEN STARTUP OPTIONS
# These options define how and where Origen should boot.
# See the guides at advanced/invocations for additional details.

# By default, don't allow user install. This is more for power users to utilize for debug or those who want absolute 
# control over their environment.
user_install_enable: false

# Default to the user's install dir being the .origen in their home directory but allow it to be overridden
#user_install_dir: ~/.origen

# Default 'tool_repo_install_dir' to nil, meaning no 'tool_repo_install_dir' is present. If neither this nor 
# 'user_install_enable' is present, the universal install will be used.
#tool_repo_install_dir: nil

# If 'tool_repo_install_dir' is set, then, by default, Bundler will use and build the gems in the tool repo.
# Purpose of this, is to allow a power user to setup and install these gems and for individuals to just use.
# Added this parameter and set to true so that this will be the default behavior. Otherwise, gem_install_dir
# would need to be overwritten and set with the 'tool_repo_install_dir'
gems_use_tool_repo: true

# Some gems can be difficult to install reliably across individual user environments.
# Such gems can be installed to a communal system Ruby and then listed here, Origen
# will then use the system version of the given gem instead of trying to install
# it fresh for each user.
# Note that this option will only be applied if gem_manage_bundler is set to true.
gem_use_from_system:
  - [nokogiri, 1.6.4.1] # Only required for earlier versions of Origen
  - [nokogiri, 1.6.7.2] # Only required for earlier versions of Origen
  - [nokogiri, 1.7.2]

# Additionally any build switches/options that are required to build specific gems
# in your user environment can be defined here.
#gem_build_switches:
#  - nokogiri --use-system-libraries=true --with-xml2-include=/path/to/libxml2  
#  - other_gem --some_build_switch

# USERS AND LDAP

# Adding an email domain will allow email addresses for users to be automatically
# generated from their ID e.g.
#
#   # With email_domain specified
#   User.new("ax1234").email  # => "ax1234@company.com"  
#
#   # Without email_domain specified
#   User.new("ax1234@company.com").email  # => "ax1234@company.com"  
#email_domain: company.com
#email_server: smtp.company.net
#email_port: 25

# Required parameters to connect to your company's LDAP system
#ldap_username: cn=manager,dc=example,dc=com
#ldap_password: opensesame
#ldap_host: ids.company.net
#ldap_port: 636
#ldap_base_dn: ou=people,ou=intranet,dc=com
# Optional to override the name given to the user ID attribute on the LDAP system ('id' by default)
#ldap_user_id_attribute: uid

# LSF  
