# Where user's local gems will be installed
gem_install_dir: ~/.origen/gems

# If your company has an internal gem server enter it here
#gem_server: http://rgen-hub.am.freescale.net:9292

# If build switches/options are required to build specific gems in your environment
# you can define them here
#gem_build_switches:
#  - nokogiri --use-system-libraries=true --with-xml2-include=/path/to/libxml2  
#  - other_gem --some_build_switch
