name: Regression Tests
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby-version: [2.5, 2.6]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Ruby
    - uses: actions/checkout@v1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        CONTINUOUS_INTEGRATION: 1
    - name: Verify app can boot successfully
      run: |
        gem install bundler -v '< 2'
        bundle install --jobs 4 --retry 3
        bundle exec origen -v
    - name: Lint Check
      run: |
        bundle install
        bundle exec origen lint --no-correct
    - name: Run tests
      run: |
        bundle install
        bundle exec origen m debug
        bundle exec origen test -c
    - name: Verify Building website
      run: |
        bundle install
        bundle exec origen web compile --no-serve

      

