name: Ruby

on:
  pull_request:
    branches:
    - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.3.x
    - name: Build and test Origen
      run: |
        gem install bundler -v '< 2'
        bundle install --gemfile Gemfile --binstubs lbin --path ~/.origen/gems/
        bundle info origen
        bundle exec origen -v

