name: Ruby

on:
  pull_request:
    branches:
    - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.3.x
    - name: Build and test Origen
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec origen -v
        bundle exec origen m debug
        bundle exec origen test -c
        bundle exec origen web compile --no-serve
        bundle exec origen lint --no-correct
